### PR TITLE
search for index.js #2

### PR DESCRIPTION
**Pull request by simi**
followup to #17

I try to add specs soon.

/cc @cowboyd @ftiasch

### CODE REVIEW

**Comment by cowboyd** [comment]
Ok, this looks good. Can we add some specs for the new behavior?

**Comment by simi** [comment]
sure

**Comment by Wardrop** [comment]
Can this be merged already?

**Comment by cowboyd** [comment]
@Wardrop As you can see from the last comment this PR is waiting on specs for the added behavior so the answer to your question is no. However, if you would like to take a crack at writing those specs, I would be happy to assist in any way I can.

**Comment by ojab** [comment]
```
diff --git a/lib/commonjs/module.rb b/lib/commonjs/module.rb
index 27b318d..4529ee5 100644
--- a/lib/commonjs/module.rb
+++ b/lib/commonjs/module.rb
@@ -5,6 +5,9 @@ module CommonJS
     attr_accessor :exports

     def initialize(id, env, append = false)
+      id.sub!(%r{/index.js$}, '') if append
+      p "id: #{id}"
+      p "append: #{append}"
       @id = id
       @env = env
       @exports = env.new_object

**Comment by ojab** [comment]
At least this should be added to correctly require files in modules that was required by dirname:
```patch
diff --git a/lib/commonjs/module.rb b/lib/commonjs/module.rb
index 27b318d..4529ee5 100644
--- a/lib/commonjs/module.rb
+++ b/lib/commonjs/module.rb
@@ -5,6 +5,9 @@ module CommonJS
     attr_accessor :exports

     def initialize(id, env, append = false)
+      id.sub!(%r{/index.js$}, '') if append
       @id = id
       @env = env
       @exports = env.new_object
```

**Pull request closed without merging**
